apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace : lab3
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec: 
  storageClassName: standard
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
